import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSpinner1 = new javax.swing.JSpinner();
		jPanel1 = new javax.swing.JPanel();
		JuserID = new javax.swing.JLabel();
		textFieldID = new javax.swing.JTextField();
		jPasswordField = new javax.swing.JPasswordField();
		JuserID1 = new javax.swing.JLabel();
		jButton_Register = new javax.swing.JButton();
		jButton_Login = new javax.swing.JButton();
		jLabel_BG = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Login");
		setBackground(new java.awt.Color(153, 255, 204));

		jPanel1.setBackground(new java.awt.Color(102, 102, 102));
		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		JuserID.setBackground(new java.awt.Color(153, 204, 0));
		JuserID.setFont(new java.awt.Font("Songti TC", 0, 36)); // NOI18N
		JuserID.setForeground(new java.awt.Color(153, 51, 255));
		JuserID.setText("  User ID: ");
		jPanel1.add(JuserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 38));

		textFieldID.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textFieldIDActionPerformed(evt);
			}
		});
		jPanel1.add(textFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 230, 40));
		jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 230, 40));

		JuserID1.setBackground(new java.awt.Color(51, 102, 255));
		JuserID1.setFont(new java.awt.Font("Songti TC", 0, 36)); // NOI18N
		JuserID1.setForeground(new java.awt.Color(153, 51, 255));
		JuserID1.setText("  Password: ");
		jPanel1.add(JuserID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 38));

		jButton_Register.setBackground(new java.awt.Color(204, 255, 255));
		jButton_Register.setFont(new java.awt.Font("Kaiti TC", 0, 36)); // NOI18N
		jButton_Register.setForeground(new java.awt.Color(153, 51, 255));
		jButton_Register.setText("Register");
		jButton_Register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_RegisterActionPerformed(evt);
			}
		});
		jPanel1.add(jButton_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 160, 50));

		jButton_Login.setBackground(new java.awt.Color(204, 255, 255));
		jButton_Login.setFont(new java.awt.Font("Kaiti TC", 0, 36)); // NOI18N
		jButton_Login.setForeground(new java.awt.Color(153, 51, 255));
		jButton_Login.setText("Login");
		jButton_Login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_LoginActionPerformed(evt);
			}
		});
		jPanel1.add(jButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 120, 50));

		// jLabel_BG.setIcon(new
		// javax.swing.ImageIcon(getClass().getResource("/resources/p3.jpeg"))); //
		// NOI18N
		try {
			BufferedImage image = ImageIO.read(new File("/Users/bc/Desktop/OOPFinal/FinalProject/image/p3.jpeg"));
			//要自行更改
			jLabel_BG.setIcon(new ImageIcon(image));
		} catch (IOException e) {
			e.printStackTrace();
		}
	

		jPanel1.add(jLabel_BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 430));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void textFieldIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldIDActionPerformed
		// TODO add your handling code here:
	}

	private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_RegisterActionPerformed
		// TODO add your handling code here:
		Register reg = new Register();
		reg.setVisible(true);
		reg.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.dispose();
	}// GEN-LAST:event_jButton_RegisterActionPerformed

	private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_LoginActionPerformed
		// TODO add your handling code here:
		PreparedStatement ps;
		ResultSet rs;

		String uid = textFieldID.getText();
		String pass = String.valueOf(jPasswordField.getPassword());

		if (uid.equals("")) {
			JOptionPane.showMessageDialog(null, "Please enter your id");
		} else if (pass.equals("")) {
			JOptionPane.showMessageDialog(null, "Please enter your password");
		} else {

			String query = "SELECT * FROM `reg_form` WHERE `r_id` = ? AND `r_pass` = ?";

			try {
				ps = MySQL.connectSQL().prepareStatement(query);

				ps.setString(1, uid);
				ps.setString(2, pass);
				rs = ps.executeQuery();

				if (rs.next()) {
					JOptionPane.showMessageDialog(null, "YES");
				} else {
					JOptionPane.showMessageDialog(null, "NO");
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}// GEN-LAST:event_jButton_LoginActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}
	
	

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel JuserID;
	private javax.swing.JLabel JuserID1;
	private javax.swing.JButton jButton_Login;
	private javax.swing.JButton jButton_Register;
	private javax.swing.JLabel jLabel_BG;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField;
	private javax.swing.JSpinner jSpinner1;
	private javax.swing.JTextField textFieldID;
	// End of variables declaration//GEN-END:variables
}
