
public class Sell extends javax.swing.JFrame {

    /**
     * Creates new form Sell_Book
     */
    public Sell() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel_Photo = new javax.swing.JLabel();
        jLabel_Price = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jCB_Note = new javax.swing.JCheckBox();
        jCB_Book = new javax.swing.JCheckBox();
        jLabel_BkSitua = new javax.swing.JLabel();
        jLabel_Class = new javax.swing.JLabel();
        jCB_Major = new javax.swing.JComboBox<>();
        jLabel_Author = new javax.swing.JLabel();
        jLabel_View = new javax.swing.JLabel();
        jLabel_Upload = new javax.swing.JLabel();
        jLabel_Time = new javax.swing.JLabel();
        jLabel_UploadB = new javax.swing.JLabel();
        jButt_Upload = new javax.swing.JButton();
        jButt_Submit = new javax.swing.JButton();
        jTextF_Time = new javax.swing.JTextField();
        jTextF_Name = new javax.swing.JTextField();
        jTextF_Price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextA_View = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextA_BkSitua = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextF_Author = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//        jPanel1.setBackground(new java.awt.Color(107, 213, 229));
//
//        jDesktopPane1.setPreferredSize(new java.awt.Dimension(400, 400));
//
//        jDesktopPane1.setLayer(jLabel_Photo, javax.swing.JLayeredPane.DEFAULT_LAYER);
//
//        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
//        jDesktopPane1.setLayout(jDesktopPane1Layout);
//        jDesktopPane1Layout.setHorizontalGroup(
//            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jLabel_Photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        jDesktopPane1Layout.setVerticalGroup(
//            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jLabel_Photo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
//        );

        jLabel_Price.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Price.setText("價格");

        jLabel_Name.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Name.setText("名稱");

        jCB_Note.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jCB_Note.setText("電子筆記");
        jCB_Note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_NoteActionPerformed(evt);
            }
        });

        jCB_Book.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jCB_Book.setText("二手書");
        jCB_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_BookActionPerformed(evt);
            }
        });

        jLabel_BkSitua.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_BkSitua.setText("書況");

        jLabel_Class.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Class.setText("類別");

        jCB_Major.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        jCB_Major.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "文學院", "商學院", "理學院", "資訊學院", "社會科學學院", "法學院", "外文學院", "傳播學院", "國際事務學院", "教育學院", "創新國際學院", "國際金融學院" }));

        jLabel_Author.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Author.setText("作者/出版社");

        jLabel_View.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_View.setText("簡介");

        jLabel_Upload.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Upload.setText("上傳圖片");

        jLabel_Time.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jLabel_Time.setText("交易時間");

        jLabel_UploadB.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel_UploadB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButt_Upload.setBackground(new java.awt.Color(204, 255, 255));
        jButt_Upload.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jButt_Upload.setText("上傳");
        jButt_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_UploadActionPerformed(evt);
            }
        });

        jButt_Submit.setBackground(new java.awt.Color(181, 181, 255));
        jButt_Submit.setFont(new java.awt.Font("Helvetica Neue", 0, 22)); // NOI18N
        jButt_Submit.setText("繳交");
        jButt_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_SubmitActionPerformed(evt);
            }
        });

        jTextF_Time.setToolTipText("");
        jTextF_Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_TimeActionPerformed(evt);
            }
        });

        jTextF_Name.setToolTipText("");
        jTextF_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_NameActionPerformed(evt);
            }
        });

        jTextF_Price.setToolTipText("");
        jTextF_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_PriceActionPerformed(evt);
            }
        });

        jTextA_View.setColumns(20);
        jTextA_View.setRows(5);
        jTextA_View.setTabSize(10);
        jScrollPane1.setViewportView(jTextA_View);

        jTextA_BkSitua.setColumns(20);
        jTextA_BkSitua.setRows(5);
        jTextA_BkSitua.setTabSize(10);
        jScrollPane2.setViewportView(jTextA_BkSitua);

        jTextF_Author.setToolTipText("");
        jTextF_Author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_AuthorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextF_Time)
                            .addComponent(jLabel_View)
                            .addComponent(jLabel_BkSitua)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextF_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCB_Book)
                                .addGap(48, 48, 48)
                                .addComponent(jCB_Note))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Class)
                                .addGap(18, 18, 18)
                                .addComponent(jCB_Major, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Author)
                            .addComponent(jButt_Submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextF_Author))
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_UploadB, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addComponent(jButt_Upload))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_Upload)
                                .addGap(312, 312, 312))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Time))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Upload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_UploadB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButt_Upload))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Name)
                    .addComponent(jTextF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Price)
                    .addComponent(jTextF_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_Note)
                    .addComponent(jCB_Book))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Class)
                    .addComponent(jCB_Major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Author)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextF_Author, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_BkSitua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_View)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Time)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextF_Time, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButt_Submit)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jCB_NoteActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jCB_BookActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButt_UploadActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButt_SubmitActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextF_TimeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextF_NameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextF_PriceActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextF_AuthorActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButt_Submit;
    private javax.swing.JButton jButt_Upload;
    private javax.swing.JCheckBox jCB_Book;
    private javax.swing.JComboBox<String> jCB_Major;
    private javax.swing.JCheckBox jCB_Note;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Author;
    private javax.swing.JLabel jLabel_BkSitua;
    private javax.swing.JLabel jLabel_Class;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Photo;
    private javax.swing.JLabel jLabel_Price;
    private javax.swing.JLabel jLabel_Time;
    private javax.swing.JLabel jLabel_Upload;
    private javax.swing.JLabel jLabel_UploadB;
    private javax.swing.JLabel jLabel_View;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextA_BkSitua;
    private javax.swing.JTextArea jTextA_View;
    private javax.swing.JTextField jTextF_Author;
    private javax.swing.JTextField jTextF_Name;
    private javax.swing.JTextField jTextF_Price;
    private javax.swing.JTextField jTextF_Time;
    // End of variables declaration                   
}
